version: "2.4"
services:
    client:
        build:
          context: ./client
        container_name: "client"
        ports:
          - 4200:4200
        depends_on:
    
    api:
        build:
            context: ./nodeapi
        container_name: "api"
        ports:
            - 5000:5000
        depends_on:
          [nginx, emongo]    

    webapi: 
        build:
            context: ./javaapi
        container_name: "webapi"
        ports:
            - 9000:9000
        depends_on:
           [emartdb]

    nginx:
        image: nginx:latest
        container_name: "nginx"
        ports:
          -80:80               

            
