version: "2.4"
services:
    client:
        build:
          context: ./client
        container_name: client
        ports:
          - "4200:4200"
        depends_on:
          [api, webapi]
    
    api:
        build:
            context: ./nodeapi
        container_name: api
        ports:
            - "5000:5000"
        depends_on:
          [emongo]    

    webapi: 
        build:
            context: ./javaapi
        container_name: webapi
        restart: always
        ports:
            - "9000:9000"
        depends_on:
           [emartdb]

    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
        ports:
          - "80:80" 

    emongo:
        image: mongo:4
        container_name: emongo
        environment:
                - MONGO_INITDB_DATABASE=epoc
        ports:
            - "27017:27017"

    emartdb:
        image: mysql:5.7   
        container_name: emartdb
        environment:
                - MYSQL_ROOT_PASSWORD=emartdbpass
                - MYSQL_DATABASE=books
        ports:
            - "3306:3306"                                      

            
